services:
  api_gateway:
    build: ./http-api-gateway # Định nghĩa đường dẫn tới Dockerfile để build image cho dịch vụ này
    ports:
      - "3000:3000" # Mở cổng 3000 trên máy chủ và ánh xạ đến cổng 3000 của container
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src # Liên kết thư mục ./http-api-gateway/src đến /usr/src/app/src trên docker, giúp đồng bộ hóa mã nguồn
    command: npm run start:dev # Chạy lệnh npm run start:dev để khởi động dịch vụ
    environment:
      - PORT=3000 # Thiết lập biến môi trường với PORT 3000
  users_microservice:
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: npm run start:dev
  payments_microservice:
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: npm run start:dev
  nats:
    image: nats # Sử dụng image Docker chính thức của NATS đã có sẵn ở trên Docker
    ports:
      - 4222:4222 # Mở cổng 4222 trên máy chủ và ánh xạ đến cổng 4222 của container trên Docker
  # PostgresSQL
  postgres_db:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=socialmsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=35701537scss

  # MySQL
  # mysql_db:
  #   image: mysql
  #   ports:
  #     - "3307:3307"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root_password_123
  #     - MYSQL_DATABASE=nestjs_db
  #     - MYSQL_USER=testuser
  #     - MYSQL_PASSWORD=testuser123
  #     - MYSQL_TCP_PORT=3307
